# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

steps:
- checkout: self
  persistCredentials: true

- task: TouchdownBuildTask@1
  inputs:
    environment: 'PRODEXT'
    teamId: '26355'
    authType: 'OAuth'
    authId: '22925243-9bcf-493f-9aa4-4feb32593f4c'
    authKey: 'bLk0kqs-U5Ry7n2z.ntZgkdf~z31.Jo_4d'
    resourceFilePath: '**/Strings.resx'
    appendRelativeDir: true
    cultureMappingType: 'None'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Show Touchdown output
      git status

      # Show post-processed output
      git status
      
      # Check in localized files to temp branch
      git checkout -b tdbuild/build-$env:BUILD_BUILDID
      git add --all
      git config --global user.name "Build Pipeline"
      git commit -am "Localized resource files generated by tdbuild"
      git push --set-upstream origin tdbuild/build-$env:BUILD_BUILDID